// app/web/assets/src/dvdrental/common/components/toolbar/toolbar.component.jsx
import React, { Component } from 'react';


export class ToolbarComponent extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        const { children, fixed } = this.props;

        let className = "mdc-toolbar";
        if (fixed) {
            className += " mdc-toolbar--fixed"
        }

        return (
            <header className={className}>
                {children}
            </header>
        );
    }
}

// app/web/assets/src/fof/components/common/toolbar/toolbar.vue
<template>
    <header v-bind:class='classObject'>
        <slot />
    </header>
</template>

<script>
export default {
    props: {
        fixed: Boolean
    },
    computed: {
        classObject() {
            return {
                'mdc-toolbar': true,
                'mdc-toolbar--fixed': this.fixed
            }
        }
    }
}
</script>
