// app/web/assets/src/fof/components/common/grid/gridCell.vue
<template>
    <div v-bind:class='classObject'>
        <slot />
    </div>
</template>

<script>
let validator = (value) => {
    return value >= 1 && value <= 12;
};

export default {
    props: {
        columns: {
            type: Number,
            validator: validator
        },
        desktop: {
            type: Number,
            validator: validator
        },
        tablet: {
            type: Number,
            validator: validator
        },
        mobile: {
            type: Number,
            validator: validator
        }
    },
    computed: {
        classObject() {
            return {
                'mdc-layout-grid__cell': true,
                [`mdc-layout-grid__cell--span-${this.columns}`]: this.columns,
                [`mdc-layout-grid__cell--span-${this.desktop}-desktop`]: this.desktop,
                [`mdc-layout-grid__cell--span-${this.tablet}-tablet`]: this.tablet,
                [`mdc-layout-grid__cell--span-${this.mobile}-mobile`]: this.mobile,
            };
        }
    }
}
</script>

// app/web/assets/dvdrental/common/components/grid/gridCell.component.jsx
import React, { Component } from 'react';


export class GridCellComponent extends Component {
    constructor(props) {
        super(props);
    }

    getClass() {
        const { columns, desktop, tablet, mobile } = this.props;

        let className = 'mdc-layout-grid__cell';

        if (columns) {
            className += ` mdc-layout-grid__cell--span-${columns}`;
        }
        if (desktop) {
            className += ` mdc-layout-grid__cell--span-${desktop}-desktop`;
        }
        if (tablet) {
            className += ` mdc-layout-grid__cell--span-${tablet}-tablet`;
        }
        if (mobile) {
            className += ` mdc-layout-grid__cell--span-${mobile}-mobile`;
        }

        return className;
    }

    render() {
        const { children } = this.props;

        return (
            <div className={this.getClass()}>
                {children}
            </div>
        );
    }
}
