// app/web/assets/common/components/page/page.component.jsx
import React, { Component } from 'react';

import { Grid, GridCell } from '../grid';
import { Toolbar, ToolbarRow, ToolbarSection } from '../toolbar';

export class PageComponent extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        const { children, title } = this.props;

        let toolbarTitle = title ? title : "DvdRental";
        
        return (
            <div>
                <Toolbar fixed>
                    <ToolbarRow>
                        <ToolbarSection title align="start">
                            {toolbarTitle}
                        </ToolbarSection>
                    </ToolbarRow>
                </Toolbar>
                <main className="mdc-toolbar-fixed-adjust">
                    <Grid>
                        <GridCell desktop='2' tablet='1' />
                        <GridCell desktop='8' tablet='6' mobile='4'>
                            {children}
                        </GridCell>
                    </Grid>
                </main>
            </div>
        );
    }
}

// app/web/assets/src/fof/components/common/page/page.vue
<template>
    <div>
        <toolbar fixed>
            <toolbar-row>
                <toolbar-section align='start'>
                    <toolbar-title>
                        {{title}}
                    </toolbar-title>
                </toolbar-section>
            </toolbar-row>
        </toolbar>
        <main class='mdc-toolbar-fixed-adjust'>
            <grid>
                <grid-cell :desktop='2' :tablet='2' />
                <grid-cell :desktop='8' :tablet='6' :mobile='4'>
                    <slot />
                </grid-cell>
            </grid>
        </main>
    </div>
</template>

<script>
import grid from '../grid/grid.vue'
import gridCell from '../grid/gridCell.vue'

import toolbar from '../toolbar/toolbar.vue'
import toolbarRow from '../toolbar/toolbarRow.vue'
import toolbarSection from '../toolbar/toolbarSection.vue'
import toolbarTitle from '../toolbar/toolbarTitle.vue'

export default {
    props: {
        title: {
            type: String,
            required: true
        }
    },
    components: {
        grid,
        gridCell,
        toolbar,
        toolbarRow,
        toolbarSection,
        toolbarTitle
    }
}
</script>
