// app/web/assets/src/fof/components/common/toolbar/toolbarSection.vue
<template>
    <section v-bind:class='classObject'>
        <slot />
    </section>
</template>

<script>
export default {
    props: {
        align: {
            type: String,
            validator(value) {
                let aligns = [
                    'start',
                    'end'
                ];

                return aligns.includes(value);
            }
        }
    },
    computed: {
        classObject() {
            return {
                'mdc-toolbar__section': true,
                [`mdc-toolbar__section--align-${this.align}`]: this.align
            };
        }
    }
}
</script>

// app/web/assets/src/dvdrental/common/components/toolbar/toolbarSection.component.jsx
import React, { Component } from 'react';


export class ToolbarSectionComponent extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        const { children, align } = this.props;

        let className = "mdc-toolbar__section";
        let aligns = [
            "start",
            "end"
        ]
        if (aligns.some(a => a === align)) {
            className += ` mdc-toolbar__section--align-${align}`
        }

        return (
            <section className={className}>
                {children}
            </section>
        );
    }
}
